swagger: 2
info:
  title: Cloud Queues
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v1:
    get:
      operationId: getHomeDocument
      summary: Get home document
      description: Gets the home document.
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success.
          examples:
            application/json: |-
              {
                 "resources":{
                    "rel/queue":{
                       "href-template":"/queues/{queue_name}",
                       "href-vars":{
                          "queue_name":"param/queue_name"
                       },
                       "hints":{
                          "allow":[
                             "GET",
                             "HEAD",
                             "PUT",
                             "DELETE"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/queue-metadata":{
                       "href-template":"/queues/{queue_name}/metadata",
                       "href-vars":{
                          "queue_name":"param/queue_name"
                       },
                       "hints":{
                          "allow":[
                             "GET",
                             "PUT"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/queue-stats":{
                       "href-template":"/queues/{queue_name}/stats",
                       "href-vars":{
                          "queue_name":"param/queue_name"
                       },
                       "hints":{
                          "allow":[
                             "GET"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/queues":{
                       "href-template":"/queues{?marker,limit,detailed}",
                       "href-vars":{
                          "marker":"param/marker",
                          "detailed":"param/detailed",
                          "limit":"param/queue_limit"
                       },
                       "hints":{
                          "allow":[
                             "GET"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/post-messages":{
                       "href-template":"/v1/queues/{queue_name}/messages",
                       "href-vars":{
                          "queue_name":"param/queue_name"
                       },
                       "hints":{
                          "accept-post":[
                             "application/json"
                          ],
                          "allow":[
                             "POST"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/messages":{
                       "href-template":"/queues/{queue_name}/messages{?marker,limit,echo,include_claimed}",
                       "href-vars":{
                          "marker":"param/marker",
                          "include_claimed":"param/include_claimed",
                          "queue_name":"param/queue_name",
                          "limit":"param/messages_limit",
                          "echo":"param/echo"
                       },
                       "hints":{
                          "allow":[
                             "GET"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    },
                    "rel/claim":{
                       "href-template":"/v1/queues/{queue_name}/claims{?limit}",
                       "href-vars":{
                          "queue_name":"param/queue_name",
                          "limit":"param/claim_limit"
                       },
                       "hints":{
                          "accept-post":[
                             "application/json"
                          ],
                          "allow":[
                             "POST"
                          ],
                          "formats":{
                             "application/json":{

                             }
                          }
                       }
                    }
                 }
              }
  /v1/queues:
    get:
      operationId: listQueues
      summary: List queues
      description: Lists queues.
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success. The URI might have an invalid parameter (something other than limit, marker, or detailed), but the invalid parameter is ignored.
          examples:
            application/json: "{\r\n   \"queues\":[\r\n      {\r\n         \"href\"\
              :\"/v1/queues/036b184b28fcb548349af623079119c6a966cbc\",\r\n       \
              \  \"name\":\"036b184b28fcb548349af623079119c6a966cbc\"\r\n      },\r\
              \n      {\r\n         \"href\":\"/v1/queues/0441f28617afbdecf4887e635fd0777fb3cec38\"\
              ,\r\n         \"name\":\"0441f28617afbdecf4887e635fd0777fb3cec38\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/0f8f0eff158922874536efa9cf8412b9e0fd07a\"\
              ,\r\n         \"name\":\"0f8f0eff158922874536efa9cf8412b9e0fd07a\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/160f981379972a4a0afaee5f5394a5d960c410e\"\
              ,\r\n         \"name\":\"160f981379972a4a0afaee5f5394a5d960c410e\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/2888a4527d0a11a3d82202d800f8e90eebd60ea\"\
              ,\r\n         \"name\":\"2888a4527d0a11a3d82202d800f8e90eebd60ea\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/2ad8eeca7f53d480d8ca4885d620643bfc6a7f9\"\
              ,\r\n         \"name\":\"2ad8eeca7f53d480d8ca4885d620643bfc6a7f9\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/3926ce2051db957d76a04cb2ea2d89fd49e6894\"\
              ,\r\n         \"name\":\"3926ce2051db957d76a04cb2ea2d89fd49e6894\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/46b30ebd60186c30194039824e6405300dc0903\"\
              ,\r\n         \"name\":\"46b30ebd60186c30194039824e6405300dc0903\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/486d5af3e057ee1a430eee3ee845aeb60c900d3\"\
              ,\r\n         \"name\":\"486d5af3e057ee1a430eee3ee845aeb60c900d3\"\r\
              \n      },\r\n      {\r\n         \"href\":\"/v1/queues/58e8622645f07c7673412acbed51abb97ddb25d\"\
              ,\r\n         \"name\":\"58e8622645f07c7673412acbed51abb97ddb25d\"\r\
              \n      }\r\n   ],\r\n   \"links\":[\r\n      {\r\n         \"href\"\
              :\"/v1/queues?marker=58e8622645f07c7673412acbed51abb9\",\r\n       \
              \  \"rel\":\"next\"\r\n      }\r\n   ]\r\n}"
  /v1/queues/{queue_name}:
    put:
      operationId: createQueue
      summary: Create queue
      description: Creates a queue.
      produces:
      - application/json
      responses:
        201:
          description: |-
            The request has been fulfilled and the queue was created.
          examples:
            application/json: |-
              HTTP/1.1 201 Created
              Content-Length: 0
              Location: /v1/queues/demoqueue
    delete:
      operationId: deleteQueue
      summary: Delete queue
      description: Deletes the specified queue.
      produces:
      - application/json
      responses:
        200:
          description: |-
            The URI has invalid parameters. The invalid parameters are ignored.
          examples:
            application/json: |-
              HTTP/1.1 204 No Content
    get:
      operationId: checkQueueExists
      summary: Check queue existence
      description: "Verifies whether the specified queue\n\t\t\t\texists."
      produces:
      - application/json
      responses:
        204:
          description: |-
            The requested queue exists.
          examples:
            application/json: |-
              HTTP/1.0 204 OK
  /v1/queues/{queue_name}/metadata:
    put:
      operationId: setQueueMetadata
      summary: Set queue metadata
      description: "Sets metadata for the specified\n\t\t\t\tqueue."
      produces:
      - application/json
      responses:
        204:
          description: |-
            Success.
          examples:
            application/json: "HTTP/1.1 204 No Content\r\nLocation: /v1/queues/demoqueue/metadata"
    get:
      operationId: getQueueMetadata
      summary: Show queue metadata
      description: "Shows metadata for the specified\n\t\t\t\tqueue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success, or no metadata exists for the queue, or the URI has invalid parameters and the invalid parameters are ignored.
          examples:
            application/json: "{\r\n   \"new metadata\":\"Omega\"\r\n}"
  /v1/queues/{queue_name}/stats:
    get:
      operationId: getQueueStats
      summary: Show queue stats
      description: "Show statistics for the specified\n\t\t\t\tqueue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success, or the URI has invalid parameters, but the invalid parameters are ignored.
          examples:
            application/json: "{\r\n   \"messages\":{\r\n      \"claimed\":2409,\r\
              \n      \"free\":146929,\r\n      \"total\":149338,\r\n      \"newest\"\
              :{\r\n         \"age\":12,\r\n         \"created\":\"2013-08-12T20:45:46Z\"\
              ,\r\n         \"href\":\"/v1/queues/fizbit/messages/50b68a50d6f5b8c8a7c62b01\"\
              \r\n      },\r\n      \"oldest\":{\r\n         \"age\":63,\r\n     \
              \    \"created\":\"2013-08-12T20:44:55Z\",\r\n         \"href\":\"/v1/queues/fizbit/messages/50b68a50d6f5b8c8a7c62b01\"\
              \r\n      }\r\n   }\r\n}"
  /v1/queues/{queue_name}/messages:
    post:
      operationId: postMessage
      summary: Post message
      description: "Posts the message or messages for a\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            The URI might have invalid parameters, but the invalid parameters are ignored.
          examples:
            application/json: "{\r\n   \"partial\":false,\r\n   \"resources\":[\r\n\
              \      \"/v1/queues/demoqueue/messages/51db6f78c508f17ddc924357\",\r\
              \n      \"/v1/queues/demoqueue/messages/51db6f78c508f17ddc924358\"\r\
              \n   ]\r\n}"
    get:
      operationId: getSetMessagesByID
      summary: Get messages by ID
      description: "Gets the specified set of messages\n\t\t\t\tfrom the specified\
        \ queue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success. The URI might have invalid parameters, but invalid parameters are ignored.
          examples:
            application/json: |-
              [
                 {
                    "href":"/v1/queues/fizbit/messages/50b68a50d6f5b8c8a7c62b01",
                    "ttl":800,
                    "age":32,
                    "body":{
                       "cmd":"EncodeVideo",
                       "jobid":58229
                    }
                 },
                 {
                    "href":"/v1/queues/fizbit/messages/f5b8c8a7c62b0150b68a50d6",
                    "ttl":800,
                    "age":790,
                    "body":{
                       "cmd":"EncodeAudio",
                       "jobid":58201
                    }
                 }
              ]
    delete:
      operationId: deleteMessages
      summary: Bulk-delete messages by ID
      description: Bulk-deletes for messages.
      produces:
      - application/json
      responses:
        204:
          description: |-
            Success.
          examples:
            application/json: |-
              HTTP/1.1 204 No Content
  /v1/queues/{queue_name}/messages/{messageId}:
    get:
      operationId: getSpecificMessage
      summary: Show message details
      description: "Shows details for the specified message from the\n\t\t\t\tspecified\
        \ queue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success. The request found a matching message. The URI might have invalid parameters, but the invalid parameters are ignored.
          examples:
            application/json: "{\r\n   \"body\":{\r\n      \"event\":\"BackupStarted\"\
              \r\n   },\r\n   \"age\":240,\r\n   \"href\":\"/v1/queues/demoqueue/messages/51db6ecac508f17ddc9242ad\"\
              ,\r\n   \"ttl\":300\r\n}"
    delete:
      operationId: deleteMessage
      summary: Delete message
      description: "Deletes the specified message from the\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        204:
          description: |-
            Success.
          examples:
            application/json: |-
              HTTP/1.1 204 No Content
  /v1/queues/{queue_name}/claims:
    post:
      operationId: claimMessages
      summary: Claim messages
      description: "Claims a set of messages from a\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        201:
          description: |-
            Success.
          examples:
            application/json: "[\r\n   {\r\n      \"body\":{\r\n         \"event\"\
              :\"BackupStarted\"\r\n      },\r\n      \"age\":239,\r\n      \"href\"\
              :\"/v1/queues/demoqueue/messages/51db6f78c508f17ddc924357?claim_id=51db7067821e727dc24df754\"\
              ,\r\n      \"ttl\":300\r\n   }\r\n]"
  /v1/queues/{queue_name}/claims/{claimId}:
    get:
      operationId: queryClaim
      summary: Query claim
      description: "Queries the specified claim for a\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        200:
          description: |-
            Success. The request might have used invalid URI parameters, but invalid parameters were ignored.
          examples:
            application/json: "{\r\n  \"age\": 57,\r\n  \"href\": \"/v1/queues/demoqueue/claims/51db7067821e727dc24df754\"\
              ,\r\n  \"messages\": [\r\n    {\r\n      \"body\": {\r\n        \"event\"\
              : \"BackupStarted\"\r\n      },\r\n      \"age\": 296,\r\n      \"href\"\
              : \"/v1/queues/demoqueue/messages/51db6f78c508f17ddc924357?claim_id=51db7067821e727dc24df754\"\
              ,\r\n      \"ttl\": 300\r\n    }\r\n  ],\r\n  \"ttl\": 300\r\n}\r\n"
    patch:
      operationId: updateClaim
      summary: Update claim
      description: "Updates the specified claim for a\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        204:
          description: |-
            Success.
          examples:
            application/json: |-
              HTTP/1.1 204 No Content
    delete:
      operationId: deleteClaim
      summary: Release claim
      description: "Releases the specified claim for the\n\t\t\t\tspecified queue."
      produces:
      - application/json
      responses:
        204:
          description: |-
            Success.
          examples:
            application/json: |-
              HTTP/1.1 204 No Content
host: '{data_center}.queues.api.rackspacecloud.com'
schemes:
- http
- https
