swagger: 2
info:
  title: Cloud Networks
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v2.0/routers:
    get:
      operationId: listRouters
      summary: List Routers
      description: Lists logical routers that are accessible to the tenant who submits
        the request.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"routers\": \n    [\n        {\n          \
              \  \"status\": \"ACTIVE\",\n            \"external_gateway_info\": null,\n\
              \            \"name\": \"second_routers\",\n            \"admin_state_up\"\
              : true,\n            \"tenant_id\": \"6b96ff0cb17a4b859e1e575d221683d3\"\
              ,\n            \"id\": \"7177abc4-5ae9-4bb7-b0d4-89e94a4abf3b\"\n  \
              \      },\n        {\n            \"status\": \"ACTIVE\",\n        \
              \    \"external_gateway_info\": \n            {\n                \"\
              network_id\": \"3c5bcddd-6af9-4e6b-9c3e-c153e521cab8\"\n           \
              \ },\n            \"name\": \"router1\",\n            \"admin_state_up\"\
              : true,\n            \"tenant_id\": \"33a40233088643acb66ff6eb0ebea679\"\
              ,\n            \"id\": \"a9254bdb-2613-4a13-ac4c-adc581fba50d\"\n  \
              \      }\n    ]\n}"
    post:
      operationId: createRouter
      summary: Create Router
      description: Creates a logical router.
      produces:
      - application/json
      responses:
        201:
          description: |-
            201 response
          examples:
            application/json: |-
              {
                  "router":
                  {
                      "status": "ACTIVE",
                      "external_gateway_info": null,
                      "name": "another_router",
                      "admin_state_up": true,
                      "tenant_id": "6b96ff0cb17a4b859e1e575d221683d3",
                      "id": "8604a0de-7f6b-409a-a47c-a1cc7bc77b2e"
                   }
              }
      parameters:
      - name: router
        required: true
        in: body
        description: >
          <p>
                                  <p>A <code>router</code> object.</p>
                               </p>
      - name: name
        required: true
        in: body
        description: >
          <p>
                                  <p>The router name.</p>
                               </p>
      - name: admin_state_up
        required: true
        in: body
        description: >
          <p>
                                  <p>The administrative state of the router (<p>True</p>
          if up or
                                  <p>False</p> if down).</p>
                               </p>
  /v2.0/routers/{router_id}:
    get:
      operationId: showRouter
      summary: Show Router Details
      description: Shows details for the specified router.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\"router\": \n    {\n        \"status\": \"ACTIVE\"\
              ,\n        \"external_gateway_info\": \n        {\n            \"network_id\"\
              : \"3c5bcddd-6af9-4e6b-9c3e-c153e521cab8\"\n        },\n        \"name\"\
              : \"router1\",\n        \"admin_state_up\": true,\n        \"tenant_id\"\
              : \"33a40233088643acb66ff6eb0ebea679\",\n        \"id\": \"a9254bdb-2613-4a13-ac4c-adc581fba50d\"\
              \n    }\n}"
    put:
      operationId: updateRouter
      summary: Update Router
      description: Updates the specified router.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "router":
                  {
                      "status": "ACTIVE",
                      "external_gateway_info":
                      {
                          "network_id": "8ca37218-28ff-41cb-9b10-039601ea7e6b"
                      },
                      "name": "another_router",
                      "admin_state_up": true,
                      "tenant_id": "6b96ff0cb17a4b859e1e575d221683d3",
                      "id": "8604a0de-7f6b-409a-a47c-a1cc7bc77b2e"
                  }
              }
      parameters:
      - name: routers
        required: true
        in: body
        description: >
          <p>
                                  <p>A <code>routers</code> object.</p>
                               </p>
      - name: status
        required: true
        in: body
        description: >
          <p>
                                  <p>The router status.</p>
                               </p>
      - name: external_gateway_info
        required: true
        in: body
        description: >
          <p>
                                  <p>The <code>network_id</code>, for the external
          gateway.</p>
                               </p>
      - name: name
        required: true
        in: body
        description: >
          <p>
                                  <p>The router name.</p>
                               </p>
      - name: admin_state_up
        required: true
        in: body
        description: >
          <p>
                                  <p>The administrative state of the router. (<p>True</p>
          if up or
                                   <p>False</p> if down)</p>
                               </p>
      - name: tenant_id
        required: true
        in: body
        description: >
          <p>
                                  <p>The tenant ID.</p>
                               </p>
      - name: id
        required: true
        in: body
        description: >
          <p>
                                  <p>The router ID.</p>
                               </p>
    delete:
      operationId: deleteRouter
      summary: Delete Router
      description: Deletes the logical router and its external gateway interface.
      produces: []
      responses:
        204:
          description: |-
            204 response
  /v2.0/routers/{router_id}/add_router_interface:
    put:
      operationId: addRouterInterface
      summary: Add Interface to Router
      description: Adds an internal interface to the specified logical router.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "subnet_id": "a2f1f29d-571b-4533-907f-5803ab96ead1",
                  "port_id": "3a44f4e5-1694-493a-a1fb-393881c673a4"
              }
      parameters:
      - name: subnet_id
        required: false
        in: body
        description: >
          <p>
                                  <p>The subnet ID.</p>
                               </p>
      - name: port_id
        required: false
        in: body
        description: >
          <p>
                                  <p>The port ID.</p>
                               </p>
  /v2.0/routers/{router_id}/remove_router_interface:
    put:
      operationId: removeRouterInterface
      summary: Remove Interface from Router
      description: Removes an internal interface from the specified logical router.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "id": "8604a0de-7f6b-409a-a47c-a1cc7bc77b2e",
                  "tenant_id": "2f245a7b-796b-4f26-9cf9-9e82d248fda7",
                  "port_id": "3a44f4e5-1694-493a-a1fb-393881c673a4",
                  "subnet_id": "a2f1f29d-571b-4533-907f-5803ab96ead1"
              }
      parameters:
      - name: subnet_id
        required: false
        in: body
        description: >
          <p>
                                  <p>The subnet ID.</p>
                               </p>
      - name: port_id
        required: false
        in: body
        description: >
          <p>
                                  <p>The port ID.</p>
                               </p>
host: '{data_center}.servers.api.rackspacecloud.com'
schemes:
- http
- https
