swagger: 2
info:
  title: Cloud Networks
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /os-networksv2:
    get:
      operationId: listNetworks
      summary: List Networks
      description: Lists the networks configured for the specified tenant ID.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "networks":[
                    {
                       "cidr":"192.168.0.0/24",
                       "id":"1f84c238-b05a-4374-a0cb-aa6140032cd1",
                       "label":"new_network"
                    },
                    {
                       "id":"00000000-0000-0000-0000-000000000000",
                       "label":"public"
                    },
                    {
                       "id":"11111111-1111-1111-1111-111111111111",
                       "label":"private"
                    }
                 ]
              }
    post:
      operationId: createNetworks
      summary: Create Networks
      description: Creates a network for the specified tenant ID.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"network\": {\n        \"cidr\": \"192.168.0.0/24\"\
              , \n        \"id\": \"1ff4489e-db0e-45a6-8c9f-4616c6ef5db1\", \n   \
              \     \"label\": \"superprivate\"\n    }\n}"
      parameters:
      - name: cidr
        required: true
        in: body
        description: >
          <p>
                                  <p>The IP block from which to allocate the network.
          For example, <strong>172.16.0.0/24</strong> or <strong>2001:DB8::/64</strong>.
          For more
                                      information about CIDR notation, see
                                      <a href="http://www.rackspace.com/knowledge_center/article/using-cidr-notation">
                                        <p>
                                          Using CIDR Notation in CLoud Networks</p>
                                     </a>
                                      in the KNowledge Center.</p>
                              </p>
      - name: label
        required: true
        in: body
        description: >
          <p>
                                  <p>The name of the new network. For example, <strong>my_new_network</strong>.</p>
                              </p>
  /os-networksv2/{id}:
    get:
      operationId: showNetwork
      summary: Show Network
      description: Shows information for the specified network.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"network\": {\n        \"cidr\": \"192.168.0.0/24\"\
              , \n        \"id\": \"f212726e-6321-4210-9bae-a13f5a33f83f\", \n   \
              \     \"label\": \"superprivate_xml\"\n    }\n}"
    delete:
      operationId: deleteNetwork
      summary: Delete Network
      description: Deletes the specified network.
      produces: []
      responses:
        202:
          description: |-
            202 response
  /servers:
    post:
      operationId: attachNetworks
      summary: Provision Servers and Attach Networks
      description: Provisions a new server with specified networks.
      produces:
      - application/json
      responses:
        202:
          description: |-
            202 response
          examples:
            application/json: "{\n    \"server\": {\n        \"OS-DCF:diskConfig\"\
              : \"AUTO\",\n        \"adminPass\": \"LMoheHauXt8w\",\n        \"id\"\
              : \"ef08aa7a-b5e4-4bb8-86df-5ac56230f841\",\n        \"links\": [\n\
              \            {\n                \"href\": \"https://dfw.servers.api.rackspacecloud.com/v2/010101/servers/ef08aa7a-b5e4-4bb8-86df-5ac56230f841\"\
              ,\n                \"rel\": \"self\"\n            },\n            {\n\
              \                \"href\": \"https://dfw.servers.api.rackspacecloud.com/010101/servers/ef08aa7a-b5e4-4bb8-86df-5ac56230f841\"\
              ,\n                \"rel\": \"bookmark\"\n            }\n        ]\n\
              \    }\n}   "
      parameters:
      - name: name
        required: true
        in: body
        description: >
          <p>
                                  <p>The server name.</p>
                              </p>
      - name: imageRef
        required: true
        in: body
        description: >
          <p>
                                  <p>The image reference (either an ID or a full URL).</p>
                              </p>
      - name: flavorRef
        required: true
        in: body
        description: >
          <p>
                                  <p>The flavor reference (either an ID or a full
          URL).</p>
                              </p>
      - name: config_drive
        required: false
        in: body
        description: >
          <p>
                                  <p>Is config_drive enabled (either <p>true</p> or
          <p>false</p>).</p>
                              </p>
      - name: key_name
        required: false
        in: body
        description: >
          <p>
                                  <p>The name of the key pair.</p>
                              </p>
      - name: networks
        required: true
        in: body
        description: >
          <p>
                                  <p>Contains network uuids.</p>
                              </p>
      - name: uuid
        required: false
        in: body
        description: >
          <p>
                                  <p>By default, the server instance is provisioned
          with all Rackspace networks and isolated
                                      networks for the tenant. Optionally, to provision
          the server instance with a specific isolated
                                      tenant network, specify the UUID of the network
          in the <strong>UUID</strong>
                                      attribute. You can specify multiple UUIDs.</p>
                              </p>
      - name: OS-DCF:diskConfig
        required: false
        in: body
        description: >
          <p>
                                  <p>The disk configuration value, which is <p>AUTO</p>
          or <p>MANUAL</p>. See
                                      <a href="http://docs.rackspace.com/servers/api/v2/cs-devguide/content/ch_extensions.html">Disk
          Configuration
                                             Extension</a>.</p>
                              </p>
      - name: metadata
        required: false
        in: body
        description: >
          <p>
                                  <p>Metadata key and value pairs.</p>
                              </p>
      - name: personality
        required: false
        in: body
        description: >
          <p>
                                  <p> The container for personality file path and
          contents.</p>
                              </p>
      - name: path
        required: false
        in: body
        description: >
          <p>
                                  <p> The path for the personality file.</p>
                              </p>
      - name: contents
        required: false
        in: body
        description: >
          <p>
                                  <p> The contents of the personality file.</p>
                              </p>
  /servers/{instance_id}/os-virtual-interfacesv2:
    get:
      operationId: listInterfaces
      summary: List Virtual Interfaces
      description: 'Lists the virtual interfaces configured for a server instance. '
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"virtual_interfaces\": [\n        {\n     \
              \       \"id\": \"a589b11b-cd51-4274-8ec0-832ce799d156\", \n       \
              \     \"ip_addresses\": [\n                {\n                    \"\
              address\": \"2001:4800:7810:0512:d87b:9cbc:ff04:850c\", \n         \
              \           \"network_id\": \"ba122b32-dbcc-4c21-836e-b701996baeb3\"\
              , \n                    \"network_label\": \"public\"\n            \
              \    }, \n                {\n                    \"address\": \"64.49.226.149\"\
              , \n                    \"network_id\": \"ba122b32-dbcc-4c21-836e-b701996baeb3\"\
              , \n                    \"network_label\": \"public\"\n            \
              \    }\n            ], \n            \"mac_address\": \"BC:76:4E:04:85:0C\"\
              \n        }, \n        {\n            \"id\": \"de7c6d53-b895-4b4a-963c-517ccb0f0775\"\
              , \n            \"ip_addresses\": [\n                {\n           \
              \         \"address\": \"192.168.0.2\", \n                    \"network_id\"\
              : \"f212726e-6321-4210-9bae-a13f5a33f83f\", \n                    \"\
              network_label\": \"superprivate_xml\"\n                }\n         \
              \   ], \n            \"mac_address\": \"BC:76:4E:04:85:20\"\n      \
              \  }, \n        {\n            \"id\": \"e14e789d-3b98-44a6-9c2d-c23eb1d1465c\"\
              , \n            \"ip_addresses\": [\n                {\n           \
              \         \"address\": \"10.181.1.30\", \n                    \"network_id\"\
              : \"3b324a1b-31b8-4db5-9fe5-4a2067f60297\", \n                    \"\
              network_label\": \"private\"\n                }\n            ], \n \
              \           \"mac_address\": \"BC:76:4E:04:81:55\"\n        }\n    ]\n\
              }\n"
    post:
      operationId: createInterface
      summary: Create Virtual Interface
      description: "Creates a virtual interface for a network and attaches the network\
        \ to a server\n                instance."
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "virtual_interfaces":[
                    {
                       "mac_address":"FE:ED:FA:00:08:93",
                       "id":"045f195f-3347-487b-8e80-8ee3390eda56",
                       "ip_addresses":[
                          {
                             "address":"192.168.0.1",
                             "network_id":"196a0246-86cc-46fa-9ecf-850f67c2cb7c",
                             "network_label":"added_network"
                          }
                       ]
                    }
                 ]
              }
      parameters:
      - name: network_id
        required: true
        in: body
        description: >
          <p>
                                  <p>The ID of the network for which you want to create
          a virtual interface. You can create a virtual
                                      interface for an isolated network or for the
          Rackspace networks.</p>
                              </p>
  /servers/{instance_id}/os-virtual-interfacesv2/{interface_id}:
    delete:
      operationId: deleteInterface
      summary: Delete Virtual Interface
      description: Deletes a virtual interface from a server instance.
      produces: []
      responses:
        200:
          description: |-
            200 response
host: '{data_center}.servers.api.rackspacecloud.com'
schemes:
- http
- https
