swagger: 2
info:
  title: Cloud Servers
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v2/{tenant_id}/servers/{server_id}:
    get:
      operationId: os-extended-status-show
      summary: Show server extended status
      description: "Shows the extended status\n                attributes in the response\
        \ for a specified\n                server."
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "OS-EXT-STS:power_state": 1,
                      "OS-EXT-STS:task_state": null,
                      "OS-EXT-STS:vm_state": "active",
                      "accessIPv4": "",
                      "accessIPv6": "",
                      "addresses": {
                          "private": [
                              {
                                  "addr": "192.168.0.3",
                                  "version": 4
                              }
                          ]
                      },
                      "created": "2013-02-07T19:35:09Z",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/openstack/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "hostId": "570eff4776ab310707d11d181037337197086998a8b3305c90bf87c8",
                      "id": "ecb5e433-fa75-4db2-af3d-a29ae8618edc",
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v2/openstack/servers/ecb5e433-fa75-4db2-af3d-a29ae8618edc",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/openstack/servers/ecb5e433-fa75-4db2-af3d-a29ae8618edc",
                              "rel": "bookmark"
                          }
                      ],
                      "metadata": {
                          "My Server Name": "Apache1"
                      },
                      "name": "new-server-test",
                      "progress": 0,
                      "status": "ACTIVE",
                      "tenant_id": "openstack",
                      "updated": "2013-02-07T19:35:10Z",
                      "user_id": "fake"
                  }
              }
  /v2/{tenant_id}/servers/detail:
    get:
      operationId: os-extended-status-detail
      summary: List extended status for servers
      description: "Lists the extended status\n                attributes in the detailed\
        \ response for all\n                servers."
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "OS-EXT-STS:power_state": 1,
                          "OS-EXT-STS:task_state": null,
                          "OS-EXT-STS:vm_state": "active",
                          "accessIPv4": "",
                          "accessIPv6": "",
                          "addresses": {
                              "private": [
                                  {
                                      "addr": "192.168.0.3",
                                      "version": 4
                                  }
                              ]
                          },
                          "created": "2012-12-05T07:34:10Z",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/openstack/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "hostId": "585aa01f94eca692eff9f77ffe3eab866d8a819e97397e28c5c7df12",
                          "id": "030758aa-5c41-41c6-8fb4-29d44eb96a85",
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/servers/030758aa-5c41-41c6-8fb4-29d44eb96a85",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/servers/030758aa-5c41-41c6-8fb4-29d44eb96a85",
                                  "rel": "bookmark"
                              }
                          ],
                          "metadata": {
                              "My Server Name": "Apache1"
                          },
                          "name": "new-server-test",
                          "progress": 0,
                          "status": "ACTIVE",
                          "tenant_id": "openstack",
                          "updated": "2012-12-05T07:34:10Z",
                          "user_id": "fake"
                      }
                  ]
              }
host: '{data_center}.servers.api.rackspacecloud.com'
schemes:
- http
- https
