swagger: 2
info:
  title: Cloud Networks
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v2.0/ports:
    get:
      operationId: listPorts
      summary: List Ports
      description: Lists ports to which the tenant has access.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"ports\": [\n        {\n            \"admin_state_up\"\
              : true, \n            \"device_id\": \"\", \n            \"device_owner\"\
              : null, \n            \"fixed_ips\": [\n                {\n        \
              \            \"ip_address\": \"192.168.3.11\", \n                  \
              \  \"subnet_id\": \"739ecc58-f9a0-4145-8a06-cd415e6e5c8d\"\n       \
              \         }\n            ], \n            \"id\": \"10ba23f5-bb70-4fd7-a118-83f89b62e340\"\
              , \n            \"mac_address\": \"BE:CB:FE:00:00:EE\", \n         \
              \   \"name\": \"port1\", \n            \"network_id\": \"6406ed30-193a-4958-aae5-7c05268d332b\"\
              , \n            \"security_groups\": [], \n            \"status\": \"\
              ACTIVE\", \n            \"tenant_id\": \"123456\"\n        }\n    ]\n\
              }"
    post:
      operationId: bulkCreatePorts
      summary: Bulk Create Ports
      description: "Creates multiple ports in a single request. Specify a list of\
        \ ports in the request\n                body."
      produces:
      - application/json
      responses:
        201:
          description: |-
            201 response
          examples:
            application/json: |-
              {
                 "ports":[
                    {
                       "status":"DOWN",
                       "binding:host_id":null,
                       "name":"sample_port_1",
                       "admin_state_up":true,
                       "network_id":"a3775a7d-9f8b-4148-be81-c84bbd0837ce",
                       "tenant_id":"60cd4f6dbc2f491982a284e7b83b5be3",
                       "binding:vif_type":"ovs",
                       "device_owner":"",
                       "binding:capabilities":{
                          "port_filter":true
                       },
                       "mac_address":"fa:16:3e:2e:7c:8a",
                       "fixed_ips":[

                       ],
                       "id":"8fb361d8-bab0-418d-b1b8-7204a230fb06",
                       "security_groups":[
                          "99f465bc-0d7c-4142-8829-7ae0179f2fa8"
                       ],
                       "device_id":""
                    },
                    {
                       "status":"DOWN",
                       "binding:host_id":null,
                       "name":"sample_port_2",
                       "admin_state_up":false,
                       "network_id":"a3775a7d-9f8b-4148-be81-c84bbd0837ce",
                       "tenant_id":"60cd4f6dbc2f491982a284e7b83b5be3",
                       "binding:vif_type":"ovs",
                       "device_owner":"",
                       "binding:capabilities":{
                          "port_filter":true
                       },
                       "mac_address":"fa:16:3e:0a:4e:13",
                       "fixed_ips":[

                       ],
                       "id":"d4c93b0b-f593-424e-a199-d648478a5a3c",
                       "security_groups":[
                          "99f465bc-0d7c-4142-8829-7ae0179f2fa8"
                       ],
                       "device_id":""
                    }
                 ]
              }
  /v2.0/ports/{port_id}:
    get:
      operationId: showPort
      summary: Show Port
      description: Shows information for a specified port.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n    \"port\":\n        {\n            \"admin_state_up\"\
              : true, \n            \"device_id\": \"\", \n            \"device_owner\"\
              : null, \n            \"fixed_ips\": [\n                {\n        \
              \            \"ip_address\": \"192.168.3.11\", \n                  \
              \  \"subnet_id\": \"739ecc58-f9a0-4145-8a06-cd415e6e5c8d\"\n       \
              \         }\n            ], \n            \"id\": \"10ba23f5-bb70-4fd7-a118-83f89b62e340\"\
              , \n            \"mac_address\": \"BE:CB:FE:00:00:EE\", \n         \
              \   \"name\": \"port1\", \n            \"network_id\": \"6406ed30-193a-4958-aae5-7c05268d332b\"\
              , \n            \"security_groups\": [], \n            \"status\": \"\
              ACTIVE\", \n            \"tenant_id\": \"123456\"\n        }\n}"
    put:
      operationId: updatePort
      summary: Update Port
      description: Updates a specified port.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: "{\n   \"port\":\n      {\n         \"admin_state_up\"\
              :true,\n         \"device_id\": \"\",\n         \"device_owner\": null,\n\
              \         \"fixed_ips\": [\n             {\n                 \"ip_address\"\
              : \"fc01::8\",\n                 \"subnet_id\": \"1d18d76b-a04a-4147-a04c-151630ec80d0\"\
              \n             }\n         ],\n         \"id\":\"8fb361d8-bab0-418d-b1b8-7204a230fb06\"\
              ,\n         \"mac_address\":\"fa:16:3e:2e:7c:8a\",\n         \"name\"\
              :\"sample_port_1\",\n         \"network_id\":\"a3775a7d-9f8b-4148-be81-c84bbd0837ce\"\
              ,\n         \"security_groups\":[],\n         \"status\": \"ACTIVE\"\
              ,\n         \"tenant_id\":\"60cd4f6dbc2f491982a284e7b83b5be3\" \n  \
              \    }\n}"
      parameters:
      - name: port
        required: true
        in: body
        description: >
          <p>
                                  <p>The container for the port details.</p>
                               </p>
      - name: name
        required: false
        in: body
        description: >
          <p>
                                  <p>A symbolic name for the port.</p>
                               </p>
      - name: device_id
        required: false
        in: body
        description: >
          <p>
                                  <p>The ID of the port device.</p>
                               </p>
    delete:
      operationId: removePort
      summary: Delete Port
      description: Deletes a specified port.
      produces:
      - application/json
      responses:
        204:
          description: |-
            204 response
host: '{data_center}.servers.api.rackspacecloud.com'
schemes:
- http
- https
