swagger: 2
info:
  title: Cloud Identity
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v2.0/users/{userId}/OS-KSADM/credentials:
    post:
      operationId: addUserCredential
      summary: Add user credential
      description: Adds a credential to a user.
      produces:
      - application/json
      responses:
        201:
          description: |-
            201 response
          examples:
            application/json: |-
              {
                  "auth": {
                      "RAX-KSKEY:apiKeyCredentials": {
                          "username": "demoauthor",
                          "apiKey": "aaaaa-bbbbb-ccccc-12345678"
                      }
                  }
              }
    get:
      operationId: listCredentials
      summary: List Credentials
      description: "\n                List credentials.\n            "
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 203 response
          examples:
            application/json: |-
              {
              "credentials":[{
              "passwordCredentials":{
              "username":"test_user",
              "password":"mypass"
              }
              },
              {
              "RAX-KSKEY:apiKeyCredentials":{
              "username":"test_user",
              "apiKey":"aaaaa-bbbbb-ccccc-12345678"
              }
              }
              ],
              "credentials_links":[]
              }
        203:
          description: |-
            200 203 response
          examples:
            application/json: |-
              {
              "credentials":[{
              "passwordCredentials":{
              "username":"test_user",
              "password":"mypass"
              }
              },
              {
              "RAX-KSKEY:apiKeyCredentials":{
              "username":"test_user",
              "apiKey":"aaaaa-bbbbb-ccccc-12345678"
              }
              }
              ],
              "credentials_links":[]
              }
host: identity.api.rackspacecloud.com
schemes:
- http
- https
