swagger: 2
info:
  title: Cloud Files
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v1/{account}:
    get:
      operationId: listCDNcontainers
      summary: List CDN-enabled containers
      description: "Lists CDN-enabled containers\n                sorted by name."
      produces: []
      responses:
        200:
          description: |-
            The request succeeded. The information returned with the response is dependent on the method used in the request.
  /v1/{account}/{container}:
    put:
      operationId: enableDisableCDNcontainer
      summary: CDN-enable and CDN-disable a container
      description: "Enables or disables a container for\n                use with\
        \ the CDN."
      produces: []
      responses:
        200:
          description: |-
            The request has succeeded. The information returned with the response is dependent on the method used in the request.
    head:
      operationId: retrieveCDNcontainermeta
      summary: List metadata for CDN-enabled container
      description: "Gets a CDN-enabled container's\n                metadata."
      produces:
      - application/json
      responses:
        200:
          description: |-
            The request has succeeded. The information returned with the response is dependent on the method used in the request.
          examples:
            application/json: |-
              [
               {"name":"test_container",
               "cdn_enabled":"true",
               "ttl":28800,
               "log_retention":"true",
               "cdn_uri":"http://80745c48926cd286a5a0-48261ebe0e4c795a565ece6b9cca2fe8.
               r10.cf1.rackcdn.com",
               "cdn_ssl_uri":"https://
               83c49b9a2f7ad18250b3-346eb45fd42c58ca13011d659bfc1ac1.ssl.stg2.rackcdn.com",
               "cdn_streaming_uri":"http://
               80745c48926cd286a5a0-48261ebe0e4c795a565ece6b9cca2fe8.r10.cf1.rackcdn.com"}
              ]
    post:
      operationId: updateCDNcontainermeta
      summary: Update CDN-enabled container metadata
      description: "Updates the CDN-enabled container's\n                metadata."
      produces: []
      responses:
        204:
          description: |-
            The server fulfilled the request but does not need to return a body.
  /v1/{account}/{object}:
    delete:
      operationId: deleteCDNobject
      summary: Delete CDN-enabled object
      description: Deletes CDN-enabled objects.
      produces: []
      responses:
        204:
          description: |-
            The server fulfilled the request but does not need to return a body.
host: '{server}.clouddrive.com'
schemes:
- http
- https
