swagger: 2
info:
  title: Cloud Networks
  version: unknown
consumes:
- application/json
produces:
- application/json
paths:
  /v2.0/security-groups:
    get:
      operationId: listSecGroups
      summary: List Security Groups
      description: Lists all Cloud Networks security groups to which the specified
        tenant has access.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "security_groups":[
                    {
                       "description":"default",
                       "id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "name":"default",
                       "security_group_rules":[
                          {
                             "direction":"egress",
                             "ethertype":"IPv6",
                             "id":"3c0e45ff-adaf-4124-b083-bf390e5482ff",
                             "port_range_max":null,
                             "port_range_min":null,
                             "protocol":null,
                             "remote_group_id":null,
                             "remote_ip_prefix":null,
                             "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                          },
                          {
                             "direction":"egress",
                             "ethertype":"IPv4",
                             "id":"93aa42e5-80db-4581-9391-3a608bd0e448",
                             "port_range_max":null,
                             "port_range_min":null,
                             "protocol":null,
                             "remote_group_id":null,
                             "remote_ip_prefix":null,
                             "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                          },
                          {
                             "direction":"ingress",
                             "ethertype":"IPv6",
                             "id":"c0b09f00-1d49-4e64-a0a7-8a186d928138",
                             "port_range_max":null,
                             "port_range_min":null,
                             "protocol":null,
                             "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "remote_ip_prefix":null,
                             "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                          },
                          {
                             "direction":"ingress",
                             "ethertype":"IPv4",
                             "id":"f7d45c89-008e-4bab-88ad-d6811724c51c",
                             "port_range_max":null,
                             "port_range_min":null,
                             "protocol":null,
                             "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "remote_ip_prefix":null,
                             "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                             "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                          }
                       ],
                       "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                    }
                 ]
              }
    post:
      operationId: createSecGroup
      summary: Create Security Group
      description: Creates a Cloud Networks security group.
      produces:
      - application/json
      responses:
        201:
          description: |-
            201 response
          examples:
            application/json: |-
              {
                 "security_group":{
                    "description":"security group for webservers",
                    "id":"2076db17-a522-4506-91de-c6dd8e837028",
                    "name":"new-webservers",
                    "security_group_rules":[
                       {
                          "direction":"egress",
                          "ethertype":"IPv4",
                          "id":"38ce2d8e-e8f1-48bd-83c2-d33cb9f50c3d",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"2076db17-a522-4506-91de-c6dd8e837028",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       },
                       {
                          "direction":"egress",
                          "ethertype":"IPv6",
                          "id":"565b9502-12de-4ffd-91e9-68885cff6ae1",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"2076db17-a522-4506-91de-c6dd8e837028",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       }
                    ],
                    "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                 }
              }
      parameters:
      - name: name
        required: true
        in: body
        description: >
          <p>
                                  <p>A symbolic name for the security
                                      group. Not required to be unique.</p>
                               </p>
      - name: description
        required: false
        in: body
        description: >
          <p>
                                  <p>Describes the security
                                  group.</p>
                               </p>
  /v2.0/security-groups/{security_group_id}:
    get:
      operationId: showSecGroup
      summary: Show Security Group
      description: Shows information for a specified security group.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "security_group":{
                    "description":"default",
                    "id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                    "name":"default",
                    "security_group_rules":[
                       {
                          "direction":"egress",
                          "ethertype":"IPv6",
                          "id":"3c0e45ff-adaf-4124-b083-bf390e5482ff",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       },
                       {
                          "direction":"egress",
                          "ethertype":"IPv4",
                          "id":"93aa42e5-80db-4581-9391-3a608bd0e448",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       },
                       {
                          "direction":"ingress",
                          "ethertype":"IPv6",
                          "id":"c0b09f00-1d49-4e64-a0a7-8a186d928138",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "remote_ip_prefix":null,
                          "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       },
                       {
                          "direction":"ingress",
                          "ethertype":"IPv4",
                          "id":"f7d45c89-008e-4bab-88ad-d6811724c51c",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "remote_ip_prefix":null,
                          "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       }
                    ],
                    "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                 }
              }
    delete:
      operationId: deleteSecGroup
      summary: Delete Security Group
      description: Deletes a Cloud Networks security group.
      produces: []
      responses:
        204:
          description: |-
            204 response
  /v2.0/security-group-rules:
    get:
      operationId: listSecGroupRules
      summary: List Security Group Rules
      description: "Lists a summary of all Cloud Networks security group rules that\
        \ the specified tenant can\n                access."
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "security_group_rules":[
                    {
                       "direction":"egress",
                       "ethertype":"IPv6",
                       "id":"3c0e45ff-adaf-4124-b083-bf390e5482ff",
                       "port_range_max":null,
                       "port_range_min":null,
                       "protocol":null,
                       "remote_group_id":null,
                       "remote_ip_prefix":null,
                       "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                    },
                    {
                       "direction":"egress",
                       "ethertype":"IPv4",
                       "id":"93aa42e5-80db-4581-9391-3a608bd0e448",
                       "port_range_max":null,
                       "port_range_min":null,
                       "protocol":null,
                       "remote_group_id":null,
                       "remote_ip_prefix":null,
                       "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                    },
                    {
                       "direction":"ingress",
                       "ethertype":"IPv6",
                       "id":"c0b09f00-1d49-4e64-a0a7-8a186d928138",
                       "port_range_max":null,
                       "port_range_min":null,
                       "protocol":null,
                       "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "remote_ip_prefix":null,
                       "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                    },
                    {
                       "direction":"ingress",
                       "ethertype":"IPv4",
                       "id":"f7d45c89-008e-4bab-88ad-d6811724c51c",
                       "port_range_max":null,
                       "port_range_min":null,
                       "protocol":null,
                       "remote_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "remote_ip_prefix":null,
                       "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                       "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                    }
                 ]
              }
    post:
      operationId: createSecGroupRule
      summary: Create Security Group Rule
      description: Creates a Cloud Networks security group rule.
      produces:
      - application/json
      responses:
        201:
          description: |-
            201 response
          examples:
            application/json: |-
              {
                 "security_group":{
                    "description":"security group for webservers",
                    "id":"2076db17-a522-4506-91de-c6dd8e837028",
                    "name":"new-webservers",
                    "security_group_rules":[
                       {
                          "direction":"egress",
                          "ethertype":"IPv4",
                          "id":"38ce2d8e-e8f1-48bd-83c2-d33cb9f50c3d",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"2076db17-a522-4506-91de-c6dd8e837028",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       },
                       {
                          "direction":"egress",
                          "ethertype":"IPv6",
                          "id":"565b9502-12de-4ffd-91e9-68885cff6ae1",
                          "port_range_max":null,
                          "port_range_min":null,
                          "protocol":null,
                          "remote_group_id":null,
                          "remote_ip_prefix":null,
                          "security_group_id":"2076db17-a522-4506-91de-c6dd8e837028",
                          "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                       }
                    ],
                    "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                 }
              }
      parameters:
      - name: name
        required: true
        in: body
        description: >
          <p>
                                  <p>The security group
                                  name.</p>
                               </p>
      - name: description
        required: true
        in: body
        description: >
          <p>
                                  <p>The security group
                                  description.</p>
                               </p>
      - name: direction
        required: true
        in: body
        description: >
          <p>The direction in which the security group
                                  rule is applied (either <code>ingress</code> or
          <code>egress</code>). For a Cloud Servers instance,
                                  an ingress security group rule is applied to incoming
          (ingress) traffic for that instance. An egress
                                  rule is applied to traffic leaving the instance.</p>
      - name: security_group_id
        required: true
        in: body
        description: >
          <p>The security group ID to associate with
                                  this security group rule.</p>
      - name: port_range_min
        required: false
        in: body
        description: >
          <p>The minimum port number in the range that
                                  is matched by the security group rule. If the protocol
          is <p>TCP</p> or
                                      <p>UDP</p>, this value must be less than or
          equal to the value of the
                                      <p>port_range_max</p> parameter. If the protocol
          is <p>ICMP</p>, this
                                  value must be an <code>ICMP</code> type.</p>
      - name: port_range_max
        required: false
        in: body
        description: >
          <p>The maximum port number in the range that
                                  is matched by the security group rule. The <p>port_range_min</p>
          parameter constrains
                                  this parameter. If the protocol is <p>ICMP</p>,
          this value must be an <code>ICMP</code>
                                  type.</p>
      - name: protocol
        required: false
        in: body
        description: >
          <p>The protocol that is matched by the
                                  security group rule. Valid values are <code>null</code>,
          <code>tcp</code>, <code>udp</code>, and
                                      <code>icmp</code>.</p>
      - name: remote_group_id
        required: false
        in: body
        description: >
          <p>The remote group ID to be associated with
                                  this security group rule. You can specify either
          <p>remote_group_id</p> or
                                      <p>remote_ip_prefix</p> in the request body.</p>
      - name: remote_ip_prefix
        required: false
        in: body
        description: >
          <p>The remote IP prefix to be associated with
                                  this security group rule. You can specify either
          <p>remote_group_id</p> or
                                      <p>remote_ip_prefix</p> in the request body.
          This parameter matches the specified
                                  IP prefix as the source IP address of the IP packet.</p>
  /v2.0/security-group-rules/{rules-security-groups-id}:
    get:
      operationId: showSecGroupRule
      summary: Show Security Group Rule
      description: Shows detailed information for the specified security group rule.
      produces:
      - application/json
      responses:
        200:
          description: |-
            200 response
          examples:
            application/json: |-
              {
                 "security_group_rule":{
                    "direction":"egress",
                    "ethertype":"IPv6",
                    "id":"3c0e45ff-adaf-4124-b083-bf390e5482ff",
                    "port_range_max":null,
                    "port_range_min":null,
                    "protocol":null,
                    "remote_group_id":null,
                    "remote_ip_prefix":null,
                    "security_group_id":"85cc3048-abc3-43cc-89b3-377341426ac5",
                    "tenant_id":"e4f50856753b4dc6afee5fa6b9b6c550"
                 }
              }
    delete:
      operationId: deleteSecGroupRule
      summary: Delete Security Group Rule
      description: Deletes the specified rule from a Cloud Networks security group.
      produces: []
      responses:
        204:
          description: |-
            204 response
host: '{data_center}.servers.api.rackspacecloud.com'
schemes:
- http
- https
